import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import hillsImage from "../public/pattern-hills.svg";
import facebook from "../public/icon-facebook.svg";
import pinterest from "../public/icon-pinterest.svg";
import instagram from "../public/icon-instagram.svg";
import Countdown from "../components/countdown";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Launch countdown timer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.image}>
          <Image src={hillsImage} />
        </div>
        <main className={styles.main}>
          <h1 className={styles.header}>We’re launching soon</h1>
          <Countdown />
        </main>

        <footer className={styles.footer}>
          <div className={styles.social}>
            <Image src={facebook} alt="facebook" />
            <Image src={pinterest} alt="pinterest" />
            <Image src={instagram} alt="instagram" />
          </div>
        </footer>
      </div>
    </>
  );
};

export default Home;
